/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    fontFamily: {
      sans: [
        "IBM Plex Sans Thai",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      kondolar: [
        "Kondolar Thai",
        "ui-serif",
        "Georgia",
        "Cambria",
        "Times New Roman",
        "Times",
        "serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      ibmplex: [
        "IBM Plex Sans Thai",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
    screens: {
      md: "1024px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: colors.black,
      white: colors.white,
      wv: "#3904e9",
      bg: "#fffcf1",
      senate: {
        green: "#177932",
        blue: "#1152b5",
        pink: "#ffa9d1",
      },
      vote: {
        เห็น: "#60C1AF",
        ไม่เห็น: "#F92D46",
        งด: "#C5C5C5",
        ไม่ลง: "#eee",
        ไม่เข้า: "#000",
      },
      พลังประชารัฐ: "#2276EF",
      ก้าวไกล: "#FF711E",
    },
    spacing: {
      0: "0",
      4: "4px",
      5: "5px",
      10: "10px",
      15: "15px",
      20: "20px",
      30: "30px",
      40: "40px",
      50: "50px",
      60: "60px",
      80: "80px",
      100: "100px",
      120: "120px",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      1: "1px",
      2: "2px",
    },
    borderRadius: {
      5: "5px",
      10: "10px",
      full: "9999px",
    },
    extend: {
      gridTemplateRows: {
        "0fr": "0fr",
        "1fr": "1fr",
      },
      gridTemplateColumns: {
        choosepm: "1fr auto auto",
      },
    },
  },
  plugins: [],
};
